name: Jira Proxy Trigger for Jenkins

on:
  repository_dispatch:
    types: [jira-validate]

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest
    env:
      JENKINS_URL: ${{ secrets.JENKINS_URL }}
      JENKINS_USERNAME: ${{ secrets.JENKINS_USERNAME }}
      JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
      JOB_NAME: ${{ secrets.JOB_NAME }}
    steps:
      - name: Trigger Jenkins Job from Jira
        run: |
          # Branch is Jira parent key
          BRANCH="${{ github.event.client_payload.branch }}"
          # Jira issue key replaces Git commit
          JIRA_ISSUE_KEY="${{ github.event.client_payload.issue }}"
          
          # Convert labels array to comma-separated string
          LABEL_NAMES="${{ github.event.client_payload.labels }}"
          
          # Construct Jenkins URL
          URL="$JENKINS_URL/job/$JOB_NAME/buildWithParameters?PR_BRANCH=${BRANCH}&JIRA_ISSUE_KEY=${JIRA_ISSUE_KEY}&LABELS=${LABEL_NAMES}"

          echo "Triggering Jenkins with URL: ${URL}"
          curl -X POST "$URL" --user "$JENKINS_USERNAME:$JENKINS_TOKEN"
