name: Proxy Trigger for Jenkins

on:
  repository_dispatch:
    types: [validate-pr]

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest
    env:
      JENKINS_URL: ${{ secrets.JENKINS_URL }}
      JENKINS_USERNAME: ${{ secrets.JENKINS_USERNAME }}
      JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
      JOB_NAME: ${{ secrets.JOB_NAME }}
    steps:
      - name: Trigger Jenkins Job
        run: |          
          BRANCH="${{ github.event.client_payload.branch }}"
          COMMIT="${{ github.event.client_payload.commit }}"
          LABELS_JSON="${{ github.event.client_payload.labels }}"
          LABEL_NAMES=$(echo "$LABELS_JSON" | jq -r '.[].name' | paste -sd "," -)
          URL="$JENKINS_URL/job/$JOB_NAME/buildWithParameters?PR_BRANCH=${BRANCH}&GIT_COMMIT=${COMMIT}&LABELS=${LABEL_NAMES}"

          echo "Triggering Jenkins with URL: ${URL}"
          curl -X POST "$URL" --user "$JENKINS_USERNAME:$JENKINS_TOKEN"
